name: compilar e rodar os teste tudo

on:
  push:
    branches:
    - main
jobs:
   build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    steps:
      - uses: actions/checkout@v2
      - name: gogogo
        run: gcc ../src/ehpositivo.c ./test_ehpositivo.c -lrt -lm -o programa_teste && ./programa_teste
